name: Deployment
on:
  push:
    branches: [ master ]

jobs:
  dev_deploy:
    name: Dev Deploy
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: SSH Remote Commands Dev Deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 143.198.58.137
          username: root
          key: ${{ secrets.DEV_KEY }}
          port: 22
          script: |
            cd /var/www/html/equity
            git pull origin master
            git status